### ISSUE TITLE
How i can start this under amd gpu?

### ISSUE THREAD

**Issue by Enmton** [spawn9859/Spawn-AIm#2]
Hey,
how i can start this under amd gpu?
which config settings i need?
greeetz

**Comment by spawn9859** [comment]
I don't have it completely working for amd gpu as I just have an nvidia, I'm still new to this so I wouldn't really know where to begin getting it to work on AMD.

**Comment by spawn9859** [comment]
But if you have any suggestions or get it working, or if anyone else does, feel free to submit a pull request.
